CREATE TABLE IF NOT EXISTS users(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS pumps(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pressure REAL,
    temperature REAL,
    work INTEGER,
    enable BOOLEAN,
    permission BOOLEAN,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS gas_sensors(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    value REAL,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);
